import { z } from 'zod';

import { paginationQuerySchema } from './query';

export const EMBEDDING_SOURCE_TYPES = ['CHUNK', 'NOTE', 'EMAIL', 'MEETING'] as const;
export const embeddingSourceTypeSchema = z.enum(EMBEDDING_SOURCE_TYPES);

/** CHUNK excluded — chunk embeddings are only ever generated by the upload pipeline, never manually. */
export const MANUAL_EMBEDDING_SOURCE_TYPES = ['NOTE', 'EMAIL', 'MEETING'] as const;
export const manualEmbeddingSourceTypeSchema = z.enum(MANUAL_EMBEDDING_SOURCE_TYPES);

export const EMBEDDING_JOB_STATUSES = ['PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING'] as const;
export const embeddingJobStatusSchema = z.enum(EMBEDDING_JOB_STATUSES);

export const retrievalSearchQuerySchema = z.object({
  q: z.string().trim().min(1, 'Search query is required.'),
  limit: z.coerce.number().int().min(1).max(50).default(20),
});
export type RetrievalSearchQuery = z.infer<typeof retrievalSearchQuerySchema>;

export const retrievalContextQuerySchema = z.object({
  q: z.string().trim().min(1, 'A question is required.'),
  tokenBudget: z.coerce.number().int().min(100).max(100_000).optional(),
});
export type RetrievalContextQuery = z.infer<typeof retrievalContextQuerySchema>;

export const retrievalDocumentQuerySchema = z.object({
  id: z.string().min(1),
});
export type RetrievalDocumentQuery = z.infer<typeof retrievalDocumentQuerySchema>;

export const retrievalEntityQuerySchema = z.object({
  id: z.string().min(1),
});
export type RetrievalEntityQuery = z.infer<typeof retrievalEntityQuerySchema>;

export const retrievalSimilarQuerySchema = z.object({
  sourceType: embeddingSourceTypeSchema,
  sourceId: z.string().min(1),
  limit: z.coerce.number().int().min(1).max(50).default(10),
});
export type RetrievalSimilarQuery = z.infer<typeof retrievalSimilarQuerySchema>;

export const retrievalCitationsQuerySchema = z.object({
  refs: z
    .string()
    .trim()
    .min(1, 'At least one citation ref is required.')
    .transform((value) =>
      value
        .split(',')
        .map((ref) => ref.trim())
        .filter(Boolean),
    ),
});
export type RetrievalCitationsQuery = z.infer<typeof retrievalCitationsQuerySchema>;

export const embeddingJobQuerySchema = paginationQuerySchema.extend({
  status: embeddingJobStatusSchema.optional(),
});
export type EmbeddingJobQuery = z.infer<typeof embeddingJobQuerySchema>;

export const generateEmbeddingSchema = z.object({
  sourceType: manualEmbeddingSourceTypeSchema,
  sourceId: z.string().min(1),
});
export type GenerateEmbeddingInput = z.infer<typeof generateEmbeddingSchema>;

export const deleteEmbeddingQuerySchema = z.object({
  sourceType: embeddingSourceTypeSchema,
  sourceId: z.string().min(1),
});
export type DeleteEmbeddingQuery = z.infer<typeof deleteEmbeddingQuerySchema>;
